import { aToZObject } from "../objects/aToZobjects";
const letters = new aToZObject();
const fs = require("fs");

describe("testing a to z buttons work on AllRecipes site", () => {
    beforeEach(async () => {
        await letters.navigate();
        await letters.driver.manage().window().maximize()
    });
    afterAll(async () => {
        await letters.driver.quit();
    });
    test("checking each letter button takes you to right area", async () => {
        await letters.click(letters.originalRecipes);
        await letters.driver.sleep(2000);
        await letters.click(letters.aBtn);
        await letters.driver.sleep(1000);
        await letters.scroll();
        await letters.click(letters.bBtn);
        await letters.driver.sleep(1000);
        await letters.scroll();
        await letters.click(letters.cBtn);
        await letters.driver.sleep(1000);
        await letters.scroll();
        await letters.click(letters.dBtn);
        await letters.driver.sleep(1000);
        await letters.scroll();
        await letters.click(letters.eBtn);
        await letters.driver.sleep(1000);
        await letters.scroll();
        await letters.click(letters.fBtn);
        await letters.driver.sleep(1000);
        await letters.scroll();
        await letters.click(letters.gBtn);
        await letters.driver.sleep(1000);
        await letters.scroll();
        await letters.click(letters.hBtn);
        await letters.driver.sleep(1000);
        await letters.scroll();
        await letters.click(letters.iBtn);
        await letters.driver.sleep(1000);
        await letters.scroll();
        await letters.click(letters.jBtn);
        await letters.driver.sleep(1000);
        await letters.scroll();
        await letters.click(letters.kBtn);
        await letters.driver.sleep(1000);
        await letters.scroll();
        await letters.click(letters.lBtn);
        await letters.driver.sleep(1000);
        await letters.scroll();
        await letters.click(letters.mBtn);
        await letters.driver.sleep(1000);
        await letters.scroll();
        await letters.click(letters.nBtn);
        await letters.driver.sleep(1000);
        await letters.scroll();
        await letters.click(letters.oBtn);
        await letters.driver.sleep(1000);
        await letters.scroll();
        await letters.click(letters.pBtn);
        await letters.driver.sleep(1000);
        await letters.scroll();
        await letters.click(letters.qBtn);
        await letters.driver.sleep(1000);
        await letters.scroll();
        await letters.click(letters.rBtn);
        await letters.driver.sleep(1000);
        await letters.scroll();
        await letters.click(letters.sBtn);
        await letters.driver.sleep(1000);
        await letters.scroll();
        await letters.click(letters.tBtn);
        await letters.driver.sleep(1000);
        await letters.scroll();
        await letters.click(letters.uBtn);
        await letters.driver.sleep(1000);
        await letters.scroll();
        await letters.click(letters.vBtn);
        await letters.driver.sleep(1000);
        await letters.scroll();
        await letters.click(letters.wBtn);
        await letters.driver.sleep(1000);
        await letters.scroll();
        await letters.click(letters.xBtn);
        await letters.driver.sleep(1000);
        await letters.scroll();
        await letters.click(letters.yBtn);
        await letters.driver.sleep(1000);
        await letters.scroll();
        await letters.click(letters.zBtn);
        await letters.driver.sleep(1000);
        await letters.scroll();
    })
});